### ISSUE TITLE
Refactor or encapsule as trifid-plugin

### ISSUE THREAD

**Issue by l00mi** [zazuko/ckan-datasets#1]

**Comment by cristianvasquez** [comment]
@bergos should this be a new repository, such as trifid-plugin-ckan ?

**Comment by l00mi** [comment]
yes, for transition over to the use of the new plug-in i think that makes sense.

**Comment by cristianvasquez** [comment]
I would like test the plugin with real data, what would be a valid Endpoint and Organization URI ?

**Comment by cristianvasquez** [comment]
The plugin is available at: https://github.com/zazuko/trifid-plugin-ckan

**Comment by ludovicm67** [comment]
I took all the work that @cristianvasquez did on https://github.com/zazuko/trifid-plugin-ckan and imported it here.
I removed the repo to keep things clean.

I needed to fix some ESM/CJS issues, but at the end I'm getting something that just works.

I removed the creation of the Docker image, since we want it as a Trifid plugin, which is now the case.

I spent the required time to have it as a Trifid plugin here, so that it's done and we don't have to maintain two repositories.
